### ISSUE TITLE
Mobile responsive

### ISSUE THREAD

**Issue by cohen1280** [DevHunter128/RSSfeed-front#1]
Hello, @DevHunter128 
While I am using this repository, I found error in mobile field
The footer is not correct.
In order to fix this issue, How should I update current code?

**Comment by AlexT1280** [comment]
Thanks for your reaching out 
Could you share your screenshot?

**Comment by cohen1280** [comment]
![image](https://github.com/DevHunter128/RSSfeed-front/assets/142394469/d312ae15-b15b-4ddc-b5be-9da3a31a4dd5)

**Comment by AlexT1280** [comment]
Got it
This project didnt completed, so there are several issues
In order to fix this issue, you should use tailwind css
md:  sm:  lg:

something like that
I hope this can help you.

**Comment by cohen1280** [comment]
Great!!!!
